[package]
name = "nal-music-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.16.0"
fltk = "1.3.15"
fltk-theme = "0.4"
fltk-grid = "0.1"
mp3-duration = "0.1.10"